package bvb

import (
	"context"
	"errors"
	"fmt"
	"html"
	"net/url"
	"regexp"
	"strings"
	"time"
)

// OrderBook is the main-market (REGS) top-5 order book from an instrument's
// detail page ("Order book piata principala (top 5)"). BVB publishes it delayed
// (Delayed reports the page's 15-minute-delay marker), so it is a market-depth
// snapshot, not a live quote.
type OrderBook struct {
	Ticker    string      `json:"ticker"`
	Market    string      `json:"market"`     // always "REGS" (main market)
	Currency  string      `json:"currency"`   // always "RON"
	UpdatedAt time.Time   `json:"updated_at"` // "Ultima actualizare", Europe/Bucharest; zero if absent
	Delayed   bool        `json:"delayed"`    // page carries BVB's 15-min-delayed data marker (site-wide, so in practice always true)
	Bids      []BookLevel `json:"bids"`       // best (highest) first; at most 5
	Asks      []BookLevel `json:"asks"`       // best (lowest) first; at most 5
}

// BookLevel is one price level of one side of the book.
type BookLevel struct {
	Price  float64 `json:"price"`
	Volume int64   `json:"volume"` // shares
}

// The page is located by what a reader sees — the tab's label, the section
// heading, the column headers, the caption text — never by element ids or
// ASP.NET control names, which the server generates and may regenerate (the
// tab button's name embeds a GUID that changes on every render).
const (
	// tradingTabLabel is the label of the server-side tab that renders the book.
	tradingTabLabel = "Tranzactionare"
	// orderBookHeading is the title of the order book's section on that tab.
	orderBookHeading = "Order book piata principala"
)

// bookColumns are the order book's column headers (matched case-insensitively);
// the depth-bar columns around them have blank headers and are ignored.
var bookColumns = [4]string{"bid vol", "bid", "ask", "ask vol"}

var (
	formRe        = regexp.MustCompile(`(?is)<form\b.*?</form>`)
	inputTagRe    = regexp.MustCompile(`(?is)<input\b[^>]*>`)
	attrRe        = regexp.MustCompile(`([A-Za-z_:][-A-Za-z0-9_:.]*)\s*=\s*(?:"([^"]*)"|'([^']*)')`)
	bookRowRe     = regexp.MustCompile(`(?is)<tr\b[^>]*>(.*?)</tr>`)
	bookHeadRe    = regexp.MustCompile(`(?is)<th\b[^>]*>(.*?)</th>`)
	bookCellRe    = regexp.MustCompile(`(?is)<td\b[^>]*>(.*?)</td>`)
	bookUpdatedRe = regexp.MustCompile(`Ultima actualizare:\s*(\d{2}\.\d{2}\.\d{4} \d{2}:\d{2}:\d{2})`)
)

// bucharest is the exchange's time zone. Without a system tz database it falls
// back to EET (+02:00), which is an hour off during summer time.
var bucharest = func() *time.Location {
	if loc, err := time.LoadLocation("Europe/Bucharest"); err == nil {
		return loc
	}
	return time.FixedZone("EET", 2*3600)
}()

// OrderBook fetches the top-5 main-market order book for ticker. The book lives
// on the detail page's server-side "Tranzactionare" tab, so this costs two
// requests: a GET for the page's ASP.NET form state, then the tab's postback.
// An unknown ticker yields ErrUnknownSymbol; an instrument with no resting
// orders yields empty Bids/Asks.
func (c *Client) OrderBook(ctx context.Context, ticker string) (OrderBook, error) {
	pageURL := c.webURL + "/FinancialInstruments/Details/FinancialInstrumentsDetails.aspx?" +
		url.Values{"s": {ticker}}.Encode()
	body, err := c.get(ctx, pageURL)
	if err != nil {
		return OrderBook{}, err
	}
	page := string(body)
	if detailField(page, "Simbol:") == "" && firstMatch(companyNameRe, page) == "" {
		return OrderBook{}, fmt.Errorf("%w: %q", ErrUnknownSymbol, ticker)
	}

	form, err := tradingTabForm(page)
	if err != nil {
		return OrderBook{}, fmt.Errorf("bvb: order book for %q: %w", ticker, err)
	}
	body, err = c.postForm(ctx, pageURL, form)
	if err != nil {
		return OrderBook{}, err
	}
	page = string(body)

	bids, asks, updated, err := parseOrderBook(page)
	if err != nil {
		return OrderBook{}, fmt.Errorf("bvb: order book for %q: %w", ticker, err)
	}
	return OrderBook{
		Ticker:    strings.ToUpper(ticker),
		Market:    "REGS",
		Currency:  "RON",
		UpdatedAt: updated,
		Delayed:   strings.Contains(page, `class="delayedTimeImg"`),
		Bids:      bids,
		Asks:      asks,
	}, nil
}

// tradingTabForm builds the postback a browser sends when the trading tab is
// clicked: every named hidden field of the page's form (the ASP.NET state —
// __VIEWSTATE, __EVENTVALIDATION, … — whatever the page carries) plus the tab's
// submit button. The button is found by its label; its name is generated by
// the server and is echoed back as found.
func tradingTabForm(page string) (url.Values, error) {
	scope := page
	if f := formRe.FindString(page); f != "" {
		scope = f
	}
	form := url.Values{}
	button := ""
	for _, tag := range inputTagRe.FindAllString(scope, -1) {
		a := tagAttrs(tag)
		name := a["name"]
		if name == "" {
			continue // nameless inputs are not submitted
		}
		switch strings.ToLower(a["type"]) {
		case "hidden":
			form.Set(name, a["value"])
		case "submit":
			if button == "" && strings.TrimSpace(a["value"]) == tradingTabLabel {
				button = name
			}
		}
	}
	if button == "" {
		return nil, fmt.Errorf("page has no %q tab button (layout changed?)", tradingTabLabel)
	}
	form.Set(button, tradingTabLabel)
	return form, nil
}

// tagAttrs returns a start tag's quoted attributes keyed by lower-cased name,
// in any order and either quote style, with values HTML-unescaped.
func tagAttrs(tag string) map[string]string {
	attrs := map[string]string{}
	for _, m := range attrRe.FindAllStringSubmatch(tag, -1) {
		v := m[2]
		if v == "" {
			v = m[3]
		}
		attrs[strings.ToLower(m[1])] = html.UnescapeString(v)
	}
	return attrs
}

// parseOrderBook extracts both sides of the order book and its "Ultima
// actualizare" time from the trading tab. The book is the first table in the
// section under orderBookHeading (the section ends at the next <h2>), with
// columns mapped by header text; the depth bars beside them are each volume
// relative to the largest on either side, so they are derivable and skipped.
// A side's blank cells (a thin book) are skipped. A section with no table is an
// empty book (an ASP.NET GridView with zero rows renders no <table> by
// default). A page without the section is not the trading tab: an error.
func parseOrderBook(page string) (bids, asks []BookLevel, updated time.Time, err error) {
	h := strings.Index(page, orderBookHeading)
	if h < 0 {
		return nil, nil, time.Time{}, errors.New("order book section not found (layout changed?)")
	}
	section := page[h:]
	if end := strings.Index(section, "</h2>"); end >= 0 {
		if next := strings.Index(section[end:], "<h2"); next >= 0 {
			section = section[:end+next]
		}
	}

	bids, asks = []BookLevel{}, []BookLevel{}
	if t := strings.Index(section, "<table"); t >= 0 {
		table := section[t:]
		if end := strings.Index(table, "</table>"); end >= 0 {
			table = table[:end]
		}
		if bids, asks, err = parseBookTable(table); err != nil {
			return nil, nil, time.Time{}, err
		}
	}

	if m := bookUpdatedRe.FindStringSubmatch(section); m != nil {
		if t, perr := time.ParseInLocation("02.01.2006 15:04:05", m[1], bucharest); perr == nil {
			updated = t
		}
	}
	return bids, asks, updated, nil
}

// parseBookTable reads the book's rows, locating each column by its header.
// Data rows under unrecognised headers are a layout error; a table with no
// data rows — or only a one-cell message row — is an empty book.
func parseBookTable(table string) (bids, asks []BookLevel, err error) {
	col := map[string]int{}
	for i, m := range bookHeadRe.FindAllStringSubmatch(table, -1) {
		col[strings.ToLower(cellText(m[1]))] = i
	}
	var idx [4]int
	known := true
	for i, name := range bookColumns {
		var ok bool
		if idx[i], ok = col[name]; !ok {
			known = false
		}
	}

	bids, asks = []BookLevel{}, []BookLevel{}
	for _, row := range bookRowRe.FindAllStringSubmatch(table, -1) {
		cells := bookCellRe.FindAllStringSubmatch(row[1], -1)
		if len(cells) <= 1 {
			continue // header row, or a full-width message (GridView EmptyDataText)
		}
		if !known {
			return nil, nil, errors.New("order book columns not found (layout changed?)")
		}
		text := func(i int) string {
			if i >= len(cells) {
				return ""
			}
			return cellText(cells[i][1])
		}
		bidVol, bid, ask, askVol := idx[0], idx[1], idx[2], idx[3]
		if l, ok := bookLevel(text(bid), text(bidVol)); ok {
			bids = append(bids, l)
		}
		if l, ok := bookLevel(text(ask), text(askVol)); ok {
			asks = append(asks, l)
		}
	}
	return bids, asks, nil
}

// cellText is a cell's visible text: tags replaced by spaces (so "Bid<br/>Vol"
// reads "Bid Vol"), entities decoded, runs of whitespace (incl. &nbsp;)
// collapsed to one space.
func cellText(s string) string {
	return strings.Join(strings.Fields(html.UnescapeString(tagRe.ReplaceAllString(s, " "))), " ")
}

// bookLevel parses one side of a row; ok is false for a blank side.
func bookLevel(price, volume string) (BookLevel, bool) {
	l := BookLevel{Price: parseRoFloat(price), Volume: parseRoInt(volume)}
	return l, l.Price > 0 && l.Volume > 0
}
